
name: pipeline 01

on:
  push:
#     branches: [ main ]    
    branches-ignore: [main]

  workflow_dispatch:
    inputs:
      name:
        required: true
        description: Name your workflow
        type: String
        default: workflow
        options: [first,second,third,fourth]
        
      description:
        required: false
        description: Purpose of your workflow run
        type: String
        default: Business request        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  release:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a Java Job
        run: |
          echo Add other actions to release,
          echo test, and release your project.
          
  Testing:
    runs-on: ubuntu-latest
    
    needs: release
    
    steps:
      - uses:  actions/checkout@v3
      
      - name: Print this text
        run: echo, this job is complete
  
