# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]    
#     branches-ignore: [firstBranch]

  workflow_dispatch:
    inputs:
      name:
        required: true
        description: Name your workflow
        type: String
        default: workflow #1
        options: [A,B,C,D,E]
        
      description:
        required: false
        description: Purpose of your workflow run
        type: String
        default: e.g. Business request
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a Java Job
        run: |
          echo Add other actions to release,
          echo test, and release your project.
  
